### ISSUE TITLE
.兄弟你好

### ISSUE THREAD

**Issue by Timofeibb** [qin-yuhao/yolov8-rk3588#1]
你好， 在GitHub不能发消息所以我开一个issue吧， 我看见了你好像有一个alphadog c500 是不是？
开发的怎么样？能分享你给他做的功能（视频照片什么的，不一定是代码），我自己也有但是最近只做仿真。已经做过好好多东西如ocs2，vslam，mpcwbc，gridmap等等（都在仿真环境下）。最近在Isaaclab跑不起来模型，好麻烦。你做过这些？

**Comment by qin-yuhao** [comment]
我的不是c500 我的是新出的那个alphadog a2 dev q那个，我暂时还没用这个做强化学习，目前先暂时用他的api跑通
